-- This file is no longer used for manual updates.
-- The enhanced AI chat system includes an automated migration script that will handle all the database schema updates for you.
-- To run the migration, simply execute the following command from your project root:
-- npm run migrate-ai-chat
